//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAssessment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Choice
    {
        public int id { get; set; }
        public int queID { get; set; }
        public string label { get; set; }
        public double points { get; set; }
        public string isActive { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
