//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAssessment
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionXDuration
    {
        public int id { get; set; }
        public int regID { get; set; }
        public int testXQueID { get; set; }
        public System.TimeSpan requestTime { get; set; }
        public System.TimeSpan leaveTime { get; set; }
        public System.TimeSpan answeredTime { get; set; }
    
        public virtual Registration Registration { get; set; }
        public virtual TestXQuestion TestXQuestion { get; set; }
    }
}
