//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAssessment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Registration()
        {
            this.QuestionXDurations = new HashSet<QuestionXDuration>();
        }
    
        public int id { get; set; }
        public int userID { get; set; }
        public int testID { get; set; }
        public System.DateTime registrationDate { get; set; }
        public string token { get; set; }
        public string tokenExpireTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionXDuration> QuestionXDurations { get; set; }
        public virtual Test Test { get; set; }
        public virtual User User { get; set; }
    }
}
