//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAssessment
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestXPaper
    {
        public int id { get; set; }
        public int regID { get; set; }
        public int testXQuestionID { get; set; }
        public int choiceID { get; set; }
        public int answer { get; set; }
        public double markScored { get; set; }
    
        public virtual TestXQuestion TestXQuestion { get; set; }
    }
}
